on:
  pull_request:

name: "Review"

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  review:
    name: review
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Spelling
        uses: reviewdog/action-misspell@v1
        with:
          locale: "US"
          level: warning
          pattern: |
            *.md
            *.sh
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          level: warning
          reporter: github-pr-review
          hadolint_ignore: DL3006 DL3008
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: YamlLint
        uses: reviewdog/action-yamllint@v1
        with:
          level: warning
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: ActionLint
        uses: reviewdog/action-actionlint@v1
        with:
          level: warning
          reporter: github-pr-review
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Shellformat
        uses: reviewdog/action-shfmt@v1
        with:
          level: warning
          shfmt_flags: "-i 2 -ci -bn"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          level: warning
          reporter: github-pr-review
          shellcheck_flags: -x -e SC1091 -e SC2001 -e SC2002 -e SC2034 -e SC2064 -e SC2153 -e SC2317 -e SC2028
          github_token: ${{ secrets.GITHUB_TOKEN }}
